CREATE TABLE IF NOT EXISTS donors (
    id INT PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(255) NOT NULL,
    gender ENUM('male', 'female', 'other') NOT NULL,
    date_of_birth DATE NOT NULL,
    blood_group VARCHAR(5) NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    medical_conditions TEXT,
    organs_to_donate TEXT NOT NULL,
    medical_reports_path TEXT,
    id_proof_path VARCHAR(255) NOT NULL,
    donation_reason TEXT NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    odm_id VARCHAR(50) UNIQUE,
    is_verified BOOLEAN DEFAULT FALSE,
    guardian_name VARCHAR(255),
    guardian_email VARCHAR(255),
    guardian_phone VARCHAR(20),
    guardian_id_proof_path VARCHAR(255),
    guardian_confirmation BOOLEAN DEFAULT FALSE,
    policy_agreement BOOLEAN NOT NULL,
    terms_agreement BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status ENUM('active', 'inactive', 'withdrawn') DEFAULT 'active'
);
